### PR TITLE
Change project name to JossPaint

### PR DESCRIPTION
**Pull request by smolnp**

### CODE REVIEW

**Comment by maifeeulasad** [comment]
If you just wrote one command before doing this tiring work :
```
git pull
//git rebase - sometimes it's necessary too
```
It would've been way easier for both of us

**Comment by maifeeulasad** [comment]
Please **pull** first, cause this is getting really messy. A simple pull on your side could've solved all the issues.

And check [this](https://github.com/maifeeulasad/Joss-Paint/pull/25/commits/623e6504eaded51d4bd0706308d80e891a14e630#diff-0b9fe42c5f6788a7f3771b89ea17e330fb7eb4dd0a2e019103d6fd15c6e2f4d1) out. And [this](https://github.com/maifeeulasad/Joss-Paint/pull/13/commits/a6cecd07129f4424ecc27a0e275f7fe8712b468c#diff-3caa5a4e81c7c0454d6ae0ae512f6fc1e9ee3ea28488f7bbbc7400763ec7be2e) too. If you had pulled it before committing, then it is something that doesn't need to even solved. Please pull and them add commit and push.

```
This branch is 23 commits ahead, 15 commits behind maifeeulasad:main. 
```

**Comment by smolnp** [comment]
I don’t understand what should I do?

**Comment by smolnp** [comment]
The parent branch changes will affect only the renaming of the project and casting some commands to qt5 style. Also the .pro file has been modified for installation in qt5.

**Pull request closed without merging**
